### PR TITLE
Update horns_c.lua

### PR DESCRIPTION
**Pull request by Santiii733**
Add 2 horns by me

### CODE REVIEW

**Comment by JarnoVgr** [comment]
Actual sound files are missing, and you didn't update the meta XML.
Also, can you start with 1 higher number, because I've merged a PR which uses horn ID 407 already.

**Comment by Santiii733** [comment]
http://www.mediafire.com/file/4jk1uxsa5a92di0/408.mp3/file

http://www.mediafire.com/file/v9ks8ev6bor51nx/409.mp3/file

**Comment by JarnoVgr** [comment]
This PR is a mess. I'll fix it up when I have time

**Comment by Cena1** [comment]
Close this PR, I will add those 2 horns later on (I asked Santi to send the horns to me)

**Comment by Bierbuikje** [comment]
PR dismissed.

**Pull request closed without merging**
