### PR TITLE
added Trashmaster (ID 408) texture

### PR DESCRIPTION
**Pull request by NoamBenayoun**
added Trashmaster (ID 408) texture

### CODE REVIEW

**Comment by JarnoVgr** [comment]
Can you show a screenshot or something of what this change does?

**Comment by NoamBenayoun** [comment]
> 
> 
> Can you show a screenshot or something of what this change does?

This is supposed to add the paint job to the back side of the Trashmaster, I can't show a picture because I couldn't figure out how to get green coins on my private server.

**Comment by JarnoVgr** [comment]
I assume this is ok. @Cena1 Are you able to test it ingame?

**Comment by NoamBenayoun** [comment]
I can't come ingame so let me know if the texture draws properly, I'm interested.

**Comment by NoamBenayoun** [comment]
Well I'll leave it up to you guys, it always bugged me when the truck was still green even after I bought it in the shop.

**Comment by JarnoVgr** [comment]
It's not the best model for paintjobs. But I'm ok with it. Thanks for your contribution. :)

**Pull request merged**
